[package]
name = "catmate"
version = "0.1.0"
edition = "2024"

[lib]
name = "catmate"
path = "src/lib.rs"

[[bin]]
name = "catmate"
path = "src/main.rs"

[dependencies]

[profile.release]
opt-level = 3
lto = true
